name: Build

on:
  release:
    types: [published]

jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lifespikes'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Publish
        run: yarn npm:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
